# Generated by Django 3.2.15 on 2025-02-21 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutpagecontent_aboutpageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'verbose_name': 'Контент страницы "О нас"', 'verbose_name_plural': 'Контент страницы "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='aboutpageimage',
            options={'verbose_name': 'Изображение страницы "О нас"', 'verbose_name_plural': 'Изображения страницы "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name': 'Контент главной страницы', 'verbose_name_plural': 'Контент главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='homepageimage',
            options={'verbose_name': 'Изображение главной страницы', 'verbose_name_plural': 'Изображения главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpageimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='aboutpageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.aboutpagecontent', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='aboutpageimage',
            name='image',
            field=models.ImageField(upload_to='about_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.homepagecontent', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(upload_to='home_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
