# Generated by Django 3.2.15 on 2025-02-21 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='images',
            field=models.ManyToManyField(related_name='home_contents', to='main.Image'),
        ),
        migrations.AlterField(
            model_name='aboutpageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutpage_images', to='main.aboutpagecontent', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_images', to='main.homepagecontent', verbose_name='Контент'),
        ),
    ]
