# Generated by Django 3.2.15 on 2025-02-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20250221_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='images',
        ),
        migrations.AlterField(
            model_name='aboutpageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.aboutpagecontent', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.homepagecontent', verbose_name='Контент'),
        ),
    ]
