# Generated by Django 3.2.15 on 2025-02-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250221_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutpage_images', to='main.aboutpagecontent', verbose_name='Контент'),
        ),
    ]
